## <center>CITS5508 Lab sheet 1: an example notebook</center>

**File name: sample.ipynb**<br>
**Date created:** February 2022<br>
**Last modified:** February 2022<br>

You should be able to run this code very easily and quickly from beginning to end.
Just click on the first cell and press both the *Shift* key and the *Enter* key together.


## 1. Heading ....

A brief description about the task for this part ...

In [1]:
import numpy as np

a = 5
b = a**2

# To print formatted output in Python... 
print('{0:d} square = {1:d}. This is easy!'.format(a,b))
print('Python treats single-quotes the same as double-quotes as shown below.')
print("{0:d} square = {1:d}. This is easy!".format(a,b))

# The variables whose values that we want to print are put (in sequence) as arguments
# for the 'format' function. Inside the string (enclosed by single-quotes or 
# double-quotes), we refer to these arguments as 0:, 1:, 2:, etc. For integer type,
# we use letter 'd'; for floating point type, we use letter 'f'. For floating point
# type, we can specify the total number of digits and the number of decimal places
# that we want to print. 
print('Square root of {0:d} is {1:10.5f}. Cubic root of {0:d} is {2:8.5f}'.format(5, 5**2, 5**(1/3)))

# To print a blank line, use
print()
print('Hello world!')

5 square = 25. This is easy!
Python treats single-quotes the same as double-quotes as shown below.
5 square = 25. This is easy!
Square root of 5 is   25.00000. Cubic root of 5 is  1.70998

Hello world!


Maybe you need a *Markdown* cell here to explain the output of the previous *Code* cell. 

You can emphasize words in your sentences using boldface, e.g., **this is important**. You can even put in reasonably complex mathematics equations in a *Markdown* cell.

To run (or execute) a cell, click on the cell and press the *Enter* key while holding down the *Shift* key. You can merge cells, split cells, insert cells above or below the current cell.

In [2]:
# some more Python code here
# create a numpy array containing 0..9 (inclusive)
a = np.array(range(10))
print('a =', a)
print(a)
# find out the dimension of array a
print(a.shape)
# another way is to use the shape function in numpy
print(np.shape(a))
print('The last two print statements are not very meaningful as, looking just at the output,')
print("we don't know what it means.")
print('The last element of a is a[-1]. Its value is', a[-1])
print('Reversing the array a is also easy. ', a[-1::-1])

a = [0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
(10,)
(10,)
The last two print statements are not very meaningful as, looking just at the output,
we don't know what it means.
The last element of a is a[-1]. Its value is 9
Reversing the array a is also easy.  [9 8 7 6 5 4 3 2 1 0]


In [3]:
# note that variable a above is treated as a row vector as well as a column vector.
# We know about this as the shape returned by np.shape() is (10,) rather than (10,1).
# We can try a simple matrix-vector multiplication below to see how such vectors
# are treated.
a = np.array(range(3))    # make the array a bit shorter for ease of inspection
A = np.reshape(range(9), (3,3))          # please look up the reshape function yourself
print('A='), print(A), print('a='), print(a)
# Note: the code below is incorrect as it is element-wise multiplication
result = A*a
print('result='), print(result)

print('Matrix-vector multiplication: pre-multiplying a by A.')
result = A.dot(a)   # a is treated as a column vector (so the operation is legitimate)
print('result='), print(result)
print('The result above should be correct now.')

print('Matrix-vector multiplication: post-multiplying a by A.')
result = a.dot(A)   # a is treated as a row vector (so the operation is legitimate)
print('result='), print(result)

# Note that 'pre-multiplying a by A' is not the same as 'post-multiplication a by A'
# as matrix multiplications are not commutative. These two multiplications are the
# same only if matrix A is symmetric.

# now let's make variable b a column vector (a matrix with 1 column) from variable a
# and try the operations above.
b = np.reshape(a, (-1,1))   # look up the 'reshape' function yourself
print('Dimension of b is', b.shape)

result = A.dot(b)
print('A.dot(b) = '), print(result)

# You can try b.dot(A). You should see an error message.

# To post-multiply b by matrix A, you must transpose b first, to turn it into a row
# vector using the transpose operator (T): result = b.T.dot(A)
print()

A=
[[0 1 2]
 [3 4 5]
 [6 7 8]]
a=
[0 1 2]
result=
[[ 0  1  4]
 [ 0  4 10]
 [ 0  7 16]]
Matrix-vector multiplication: pre-multiplying a by A.
result=
[ 5 14 23]
The result above should be correct now.
Matrix-vector multiplication: post-multiplying a by A.
result=
[15 18 21]
Dimension of b is (3, 1)
A.dot(b) = 
[[ 5]
 [14]
 [23]]



## 2. Some simple Python examples 


In [4]:
# An example function with an optional argument.
def compute_product(number1, number2=10):
    '''
    This function returns the product of two numbers. If the second number
    is not specified, then it is assumed to be 10.
    '''
    return number1 * number2

In [5]:
print(compute_product(5, 7))
print(compute_product(5))


# Rather than printing out numbers without explaining what they are,
# we should always try to print out something more meaningful, like
# the two lines below:
result = compute_product(9)
print('The value returned by compute_product(9) is', result)

# or, if the variable 'result' represents the number of true positives then
# we can print the following:
print('The number of true positives is', result)

35
50
The value returned by compute_product(9) is 90
The number of true positives is 90


In [ ]:
# The example below has 3 optional arguments. Note that all the optional arguments
# must have their default values defined. 
def my_function(a, scale=5, offset=3, rounding=False):
    result = a * scale + offset
    if rounding:
        # rounding to the nearest integer and convert to integer
        result = np.int32(np.round(result, decimals=0))
    return result

# If you find the function difficult to understand, then you need to take some Python
# tutorials and learn Python at your own time. You should look up description about
# the 'int' and 'round' functions in the numpy package.

In [ ]:
result = my_function(6.3)
print('The result is:', result)
result = my_function(6.3, rounding=True)
print('The result is:', result)

# The order of specifying the option arguments is not important; however, you
# need to use their exact spellings.
result = my_function(7.5, offset=1.3, scale=2.5)
print('The result is:', result)

## 3. Cells in Jupyter Notebook

There are two main types of cells: *Markdown* and *Code*. A *Markdown* cell is for you to put in formatted comments between *Code* cells to help explain to the reader what is going on in your code. You can double-click on a *Markdown* cell to edit its contents. You can even have complex equations put into a *Markdown* cell, like the example shown below:

$\text{MSE}(\theta) = \frac{1}{m} \sum_{i=1}^m 
                      \left( h_\theta(\mathbf{x}^{(i)}) - y^{(i)} \right)^2$
                      
Rather than an equation on its own, mathematics symbols can appear in the same paragraph of the text, like here: The regularization coefficient $\alpha$ used in the experiment below is set to 0.5.

## 4. Navigation in Jupyter notebook

You can run the entire notebook, all the cells above the current cell, or all the cells below the current cell, etc. 

You can select a number of cells to delete, or to move them up/down. You can split the current cell by clicking your cursor at the point you want the split to take place. You can also merge the cell with the cell above or below. You can also insert a new cell below or after the current cell to experiment or test things. These cells should be removed afterwards.

You can clear all the output cells as well. This is a useful thing to do if you want to email your Jupyter notebook file to someone but it is too large to attach in your email because of many graphical outputs. Of course, this will require the recipient to run your Juyter notebook file in order to regenerate all the outputs.

**In your assignment submission, it may be necessary to clear all of your output cells so that your file is small enough to submit.**

Every now and then, you should do a *Save and Checckpoint* to make sure that all your changes are saved.

If you encounter the *dead kernel* problem, save your work and quit. Restarting Jupyter Notebook usually helps solve this problem.

## 5. More heading...

Some description about this section....

### 5.1 Subsection

Description


In [ ]:
# more code here

### 5.2 Subsection